# - Find PYSIDE
# Find PYSIDE headers and libraries.
#
#  PYSIDE_INCLUDE_DIRS - where to find PYSIDE includes.
#  PYSIDE_LIBRARIES    - List of libraries when using PYSIDE.
#  PYSIDE_FOUND        - True if PYSIDE found.

FIND_PATH( PYSIDE_INCLUDE_DIR NAMES PySide/pyside.h)
FIND_LIBRARY( PYSIDE_LIBRARY NAMES pyside-python2.7)

INCLUDE( FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS( PYSIDE DEFAULT_MSG PYSIDE_LIBRARY PYSIDE_INCLUDE_DIR)

# Copy the results to the output variables.
IF( PYSIDE_FOUND)
	SET( PYSIDE_LIBRARIES ${PYSIDE_LIBRARY})

	SET( PYSIDE_INCLUDE_DIRS	${PYSIDE_INCLUDE_DIR}/PySide
								${PYSIDE_INCLUDE_DIR}/PySide/QtCore
								${PYSIDE_INCLUDE_DIR}/PySide/QtGui
								${PYSIDE_INCLUDE_DIR}/PySide/QtOpenGL
								)
ELSE( PYSIDE_FOUND)
	SET( PYSIDE_LIBRARIES)
	SET( PYSIDE_INCLUDE_DIRS)
ENDIF( PYSIDE_FOUND)

MARK_AS_ADVANCED( PYSIDE_INCLUDE_DIR PYSIDE_LIBRARY)
