# - Find OpenColorIO
# Find OPENCOLORIO headers and libraries.
#
#  OPENCOLORIO_INCLUDE_DIRS - where to find OpenColorIO uncludes.
#  OPENCOLORIO_LIBRARIES    - List of libraries when using OpenColorIO.
#  OPENCOLORIO_FOUND        - True if OpenColorIO found.

# Look for the header file.
FIND_PATH(OPENCOLORIO_INCLUDE_DIR NAMES OpenColorIO/OpenColorIO.h)

# Look for the library.
FIND_LIBRARY(OPENCOLORIO_LIBRARY NAMES OpenColorIO)

# handle the QUIETLY and REQUIRED arguments and set OPENCOLORIO_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENCOLORIO DEFAULT_MSG OPENCOLORIO_LIBRARY OPENCOLORIO_INCLUDE_DIR)

# Copy the results to the output variables.
IF(OPENCOLORIO_FOUND)
  SET(OPENCOLORIO_LIBRARIES ${OPENCOLORIO_LIBRARY})
  SET(OPENCOLORIO_INCLUDE_DIRS ${OPENCOLORIO_INCLUDE_DIR})
ELSE(OPENCOLORIO_FOUND)
  SET(OPENCOLORIO_LIBRARIES)
  SET(OPENCOLORIO_INCLUDE_DIRS)
ENDIF(OPENCOLORIO_FOUND)

MARK_AS_ADVANCED(OPENCOLORIO_INCLUDE_DIR OPENCOLORIO_LIBRARY)
